name: pec
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  lottie: ^1.4.2
  mongo_dart: ^0.8.2
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  image_picker: 
  cloudinary_public: ^0.10.0
  cached_network_image: 
  table_calendar: ^3.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.12.2
  hive_generator: ^1.0.1
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/
    - assets/lottie/

  fonts:
    - family: Regular
      fonts:
        - asset: fonts/regular.ttf

    - family: Black
      fonts:
        - asset: fonts/black.ttf
          weight: 700

    - family: Bold
      fonts:
        - asset: fonts/bold.ttf
          weight: 700
